image: node:15-alpine

before_script:
    - apk add git

stages:
    - prebuild
    - build
    - deploy

merge_upstream:
    stage: prebuild
    script:
        # this ensure we are up-to-date with upstream
        - git checkout dev
        - git remote add upstream https://github.com/nrenner/brouter-web.git
        - git merge upstream/master
    only:
        - schedules

build:
    stage: build
    script:
        - yarn
        - yarn lint
        - yarn build
    except:
        - schedules

deploy:github:
    stage: deploy
    script:
        - >
            sed -i "s/\"version\": \".*\",/\"version\": \"$CI_COMMIT_TAG\",/g" package.json
        - yarn
        - ./node_modules/.bin/gulp --series release:init default release:zip release:publish --skipnewtag --token $GITHUB_TOKEN
    only:
        - tags@bagage/brouter-web
